### ISSUE TITLE
Difference between `DecisionTreeClassifier` and `LogisticRegression` when predicting a single sample.

### ISSUE THREAD

**Issue by tobiasraabe** [onnx/sklearn-onnx#1053]
Hi, thanks for the fantastic package! It helps me a ton to deploy little models.

I noticed a discrepancy between `DecisionTreeClassifier` and `LogisticRegression` handling the prediction of one sample.

I adapted the code from this [example](https://github.com/onnx/sklearn-onnx/blob/fdb52cec86d4d19401cc365db97650fd7692676b/docs/examples/plot_logging.py#L37).

I usually use the following code to build an ONNX model that predicts a single sample. Changes to the example are marked with comments.

```python
import numpy
import onnxruntime as rt
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from skl2onnx.common.data_types import FloatTensorType
from skl2onnx import convert_sklearn

iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y)

# Fitting logistic regression model.
clr = LogisticRegression()  # Use logistic regression instead of decision tree.
clr.fit(X_train, y_train)
print(clr)

initial_type = [("float_input", FloatTensorType([4]))]  # Remove the batch dimension.
onx = convert_sklearn(clr, initial_types=initial_type, target_opset=12)


sess = rt.InferenceSession(onx.SerializeToString(), providers=["CPUExecutionProvider"])
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
pred_onx = sess.run([label_name], {input_name: X_test[0].astype("float32")})[0]  # Select a single sample.
print(pred_onx)
```

This works great for me so far.

If I now replace `LogisticRegression` with `DecisionTreeClassifier`, the prediction fails with

```text
2024-01-02 16:32:33.993988537 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running TreeEnsembleClassifier node. Name:'TreeEnsembleClassifier' Status Message: /home/conda/feedstock_root/build_artifacts/onnxruntime_1697223480578/work/onnxruntime/core/providers/cpu/ml/tree_ensemble_common.h:450 void onnxruntime::ml::detail::TreeEnsembleCommon<InputType, ThresholdType, OutputType>::ComputeAgg(onnxruntime::concurrency::ThreadPool*, const onnxruntime::Tensor*, onnxruntime::Tensor*, onnxruntime::Tensor*, const AGG&) const [with AGG = onnxruntime::ml::detail::TreeAggregatorClassifier<float, float, float>; InputType = float; ThresholdType = float; OutputType = float] One path in the graph requests feature 3 but input tensor has 1 features.

Traceback (most recent call last):
  File "/home/xxx/script.py", line 41, in <module>
    pred_onx = sess.run([label_name], {input_name: X_test[0].astype("float32")})[0]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running TreeEnsembleClassifier node. Name:'TreeEnsembleClassifier' Status Message: /home/conda/feedstock_root/build_artifacts/onnxruntime_1697223480578/work/onnxruntime/core/providers/cpu/ml/tree_ensemble_common.h:450 void onnxruntime::ml::detail::TreeEnsembleCommon<InputType, ThresholdType, OutputType>::ComputeAgg(onnxruntime::concurrency::ThreadPool*, const onnxruntime::Tensor*, onnxruntime::Tensor*, onnxruntime::Tensor*, const AGG&) const [with AGG = onnxruntime::ml::detail::TreeAggregatorClassifier<float, float, float>; InputType = float; ThresholdType = float; OutputType = float] One path in the graph requests feature 3 but input tensor has 1 features.
```

To make it work, I need to add a batch dimension and reshape the input vector to two dimensions.

```python
...
initial_type = [("float_input", FloatTensorType([None, 4]))]
...
pred_onx = sess.run([label_name], {input_name: X_test[0].reshape(1, -1).astype("float32")})[0]
```

Is this an inconsistency, and can I work around the reshape? My current workaround is to use `session.get_inputs()[0].shape` and reshape inputs from 1d to 2d if necessary.

Thanks a lot in advance for your help!

**Comment by xadupre** [comment]
onnx defines TreeEnsembleClassifier https://onnx.ai/onnx/operators/onnx_aionnxml_TreeEnsembleClassifier.html#l-onnx-docai-onnx-ml-treeensembleclassifier as a function taking a 2D tensor. onnxruntime implements the standard defined by onnx. The converter could include some logics to check the dimension then add one if it is missing but it would be unnecessary in most of the cases.

**Comment by xadupre** [comment]
Closing the issue, feel free to reopen it.

**Comment by tobiasraabe** [comment]
Hi @xadupre, thanks for the explanation. I am okay with the current workaround.
