### ISSUE TITLE
SimpleImputer: Unexpected runtime error when preceded by CastTransformer

### ISSUE THREAD

**Issue by ag-tcm** [onnx/sklearn-onnx#1133]
skl2onnx Version: 1.16.0

I have a simple model where the input is numpy.float64 and the model pipeline looks like this:
```
model3 = Pipeline(
    [
        ("cast32", CastTransformer(dtype=numpy.float32)),
        ("imputer", SimpleImputer()),
        ("dt", DecisionTreeRegressor(max_depth=max_depth)),
    ]
)
...
onx3 = to_onnx(
    model3,
    initial_types=[('X', DoubleTensorType([None, 10]))], final_types=[('y', FloatTensorType([None, 1]))],
)
```
When I call `to_onnx` I get a runtime error `Inputs and outputs should have the same type` (stack trace below).

SimpleImputer should expect a FloatTensorType as its input and output type due to the transformer, but it does not.
If SimpleImputer is swapped for a StandardScaler instead, the code runs fine.

(For a full reproducible example, my sample code is based on the example here: [http://onnx.ai/sklearn-onnx/auto_tutorial/plot_ebegin_float_double.html#casttransformer](http://onnx.ai/sklearn-onnx/auto_tutorial/plot_ebegin_float_double.html#casttransformer).)

```
Traceback (most recent call last):
  File ".\src\strategy\onnx_convert_test.py", line 36, in <module>
    onx3 = to_onnx(
  File ".\lib\site-packages\skl2onnx\convert.py", line 306, in to_onnx
    return convert_sklearn(
  File ".\lib\site-packages\skl2onnx\convert.py", line 208, in convert_sklearn
    onnx_model = convert_topology(
  File ".\lib\site-packages\skl2onnx\common\_topology.py", line 1532, in convert_topology
    topology.convert_operators(container=container, verbose=verbose)
  File ".\lib\site-packages\skl2onnx\common\_topology.py", line 1349, in convert_operators
    self.call_shape_calculator(operator)
  File ".\lib\site-packages\skl2onnx\common\_topology.py", line 1164, in call_shape_calculator
    operator.infer_types()
  File ".\lib\site-packages\skl2onnx\common\_topology.py", line 653, in infer_types
    shape_calc(self)
  File ".\lib\site-packages\skl2onnx\shape_calculators\imputer.py", line 39, in calculate_sklearn_imputer_output_shapes
    raise RuntimeError(
RuntimeError: Inputs and outputs should have the same type <class 'onnxconverter_common.data_types.FloatTensorType'> != <class 'onnxconverter_common.data_types.DoubleTensorType'>.
```

**Comment by xadupre** [comment]
Did you try to move the CastTransformer after SimpleImputer?

**Comment by xadupre** [comment]
Can you try this change and tell me if it works for you?  https://github.com/onnx/sklearn-onnx/pull/1200
