### ISSUE TITLE
Converter for ColumnTransformer does not support columns specified by name

### ISSUE THREAD

**Issue by xadupre** [onnx/sklearn-onnx#32]
For an example, see issue #26 or PR #31 (unit test).

**Comment by xadupre** [comment]
This was fixed by #31.

**Comment by ivannp** [comment]
Is this fixed? I am getting an error when running both my code and https://github.com/onnx/sklearn-onnx/blob/51a9d0f3688aa3991488b8e1a3bf432147874c90/docs/examples/plot_complex_pipeline.py:

  X_test['pclass'] = X_test['pclass'].astype(str)
Traceback (most recent call last):
  File "C:\pprojects\adults-dataset-machinelearning\complex_pipeline.py", line 145, in <module>
    model_onnx = convert_sklearn(clf, 'pipeline_titanic', inputs)
  File "C:\utils\anaconda3\envs\def\lib\site-packages\skl2onnx\convert.py", line 72, in convert_sklearn
    topology = parse_sklearn(model, initial_types, target_opset, custom_conversion_functions, custom_shape_calculators)
  File "C:\utils\anaconda3\envs\def\lib\site-packages\skl2onnx\_parse.py", line 329, in parse_sklearn
    outputs = _parse_sklearn(scope, model, inputs)
  File "C:\utils\anaconda3\envs\def\lib\site-packages\skl2onnx\_parse.py", line 270, in _parse_sklearn
    return _parse_sklearn_pipeline(scope, model, inputs)
  File "C:\utils\anaconda3\envs\def\lib\site-packages\skl2onnx\_parse.py", line 188, in _parse_sklearn_pipeline
    inputs = _parse_sklearn(scope, step[1], inputs)
  File "C:\utils\anaconda3\envs\def\lib\site-packages\skl2onnx\_parse.py", line 274, in _parse_sklearn
    return _parse_sklearn_column_transformer(scope, model, inputs)
  File "C:\utils\anaconda3\envs\def\lib\site-packages\skl2onnx\_parse.py", line 245, in _parse_sklearn_column_transformer
    onnx_var, onnx_is = get_column_indices(column_indices, inputs)
  File "C:\utils\anaconda3\envs\def\lib\site-packages\skl2onnx\common\utils.py", line 235, in get_column_indices
    ov, onnx_i = get_column_index(p, inputs)
  File "C:\utils\anaconda3\envs\def\lib\site-packages\skl2onnx\common\utils.py", line 221, in get_column_index
    if pos <= i < end:
TypeError: '<=' not supported between instances of 'int' and 'str'

**Comment by xadupre** [comment]
The line number 221 seems to refer to an older version of skl2onnx. It should work if you reinstall it from the master branch. It was fixed by #31 and this file was modified by this commit. Is it possible to verify that you are using the latest version?
