### ISSUE TITLE
AttributeError: 'TypeProto' object has no attribute 'sequence_type'

### ISSUE THREAD

**Issue by cvolcy** [onnx/sklearn-onnx#34]
I'm follwing the example from the documentation.

```python
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

iris = load_iris()
X, y = iris.data, iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y)

clf = RandomForestClassifier()
clf.fit(X_train, y_train)

initial_type = [('float_input', FloatTensorType([1, 4]))]
onx = convert_sklearn(clf, initial_types=initial_type)
with open("model.onnx", "wb") as f:
    f.write(onx.SerializeToString())
```
And i'm getting an AttributeError.
```
Traceback (most recent call last):
  File "iris.py", line 17, in <module>
    onx = convert_sklearn(clf, initial_types=initial_type)
  File "C:\Users\u0306\Anaconda3\envs\onnx-tests\lib\site-packages\skl2onnx\convert.py", line 78, in convert_sklearn
    onnx_model = convert_topology(topology, name, doc_string, target_opset)
  File "C:\Users\u0306\Anaconda3\envs\onnx-tests\lib\site-packages\skl2onnx\common\_topology.py", line 708, in convert_topology
    container.add_output(other_outputs[name])
  File "C:\Users\u0306\Anaconda3\envs\onnx-tests\lib\site-packages\skl2onnx\common\_container.py", line 152, in add_output
    self.outputs.append(self._make_value_info(variable))
  File "C:\Users\u0306\Anaconda3\envs\onnx-tests\lib\site-packages\skl2onnx\common\_container.py", line 133, in _make_value_info
    value_info.type.CopyFrom(variable.type.to_onnx_type())
  File "C:\Users\u0306\Anaconda3\envs\onnx-tests\lib\site-packages\skl2onnx\common\data_types.py", line 135, in to_onnx_type
    onnx_type.sequence_type.elem_type.CopyFrom(self.element_type.to_onnx_type())
AttributeError: 'TypeProto' object has no attribute 'sequence_type'
```

**Comment by xadupre** [comment]
Is it possible to know which version of onnx you are using?

**Comment by xadupre** [comment]
The same issue was raised for onnxmltools: https://github.com/onnx/onnxmltools/issues/135. I copy paste the solution:

Please try reinstall ONNX python packages after setting `ONNX_ML=1`. If you are using windows command line, please open your cmd.exe and then do

1. C:\Users\UserName>`set ONNX_ML=1`
2. C:\Users\UserName>`pip install -I onnx` or `pip install -I git+https://github.com/onnx/onnx`
3. C:\Users\UserName>`pip install -I onnxmltools`

This should work under Window `Anaconda Prompt`, too.
