### ISSUE TITLE
BooleanTensorType not supported?

### ISSUE THREAD

**Issue by victornoel** [onnx/sklearn-onnx#399]
I tried using `convert_sklearn()` with one of my `initial_types` set to `BooleanTensorType([None, 1])`: the conversion works but then when I try to load the model with onnxruntime, I get the following error:
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (input1) of operator (ArrayFeatureExtractor) in node (ArrayFeatureExtractor) is invalid.
```

Is that expected?

**Comment by prabhat00155** [comment]
What model are you trying to convert? Can you explain the use case where you need boolean as input?

**Comment by victornoel** [comment]
@prabhat00155 I'm not sure exactly how to answer that, but here I try.

It's a model I'm building myself, it takes samples from a dataframe and some of the features are boolean values (yes or no values) and it predicts a number. You can think of it as for example a way to predict, say, prices from a set of product characteristics

It is possible I am missing something and I could convert the boolean input into another type, but my ML knowledge is not good enough to be sure what to use instead :)

For the record, my model is a pipeline with:
- a `ColumnTransformer` to encode some of the feature
  - I was planning to not encode it
- a XGBoost regressor (which supports boolean input)

**Comment by prabhat00155** [comment]
I see, for the time being, you may cast those boolean features to int using dataframe.astype(int). Meanwhile, I'll see what needs to be done in order to support bool.

**Comment by victornoel** [comment]
@prabhat00155 ok thanks. Actually, I had to cast them to float because I got the following error:
```
  File "/home/victor/.cache/pypoetry/virtualenvs/venv-51Be8MFl-py3.7/lib/python3.7/site-packages/skl2onnx/shape_calculators/concat.py", line 41, in calculate_sklearn_concat
    + inps)
RuntimeError: Columns must have the same type. C++ backends do not support mixed types. Inputs:
Variable(raw_name='variable', onnx_name='variable', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable1', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable2', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable3', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable4', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='feat1', onnx_name='has_treatment', type=Int64TensorType(shape=[None, 1]))
Variable(raw_name='feat2', onnx_name='is_beartex', type=Int64TensorType(shape=[None, 1]))
Variable(raw_name='feat3', onnx_name='is_norax', type=Int64TensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable5', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable6', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable7', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable8', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable9', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable10', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable11', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable12', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable13', type=FloatTensorType(shape=[None, 1]))
```

The other variables are the result of scalers and encoders. So I suppose that even If I can use boolean tensor variable, until the C++ backends support mixed type, it won't be practically usable, right?

**Comment by prabhat00155** [comment]
Can you paste your code here? If you can't share the entire code, just share the part where you build the model pipeline and convert it to onnx.

**Comment by victornoel** [comment]
@prabhat00155 here it is:
```py
train_df, test_df, train_labels, test_labels = train_test_split(
    full_df, full_labels, test_size=.2, random_state=None
)

col_transformer = _column_tranformer_fitted_from_df(full_df)

search = RandomizedSearchCV(
    XGBRegressor(verbose=0, objective='reg:squarederror'),
    param_distributions={
        "colsample_bytree": sp_uniform(),
        "gamma": sp_uniform(.1, 1),
        'learning_rate': sp_uniform(.1, .6),
        'max_depth': sp_randint(10, 30),
        'min_child_weight': sp_uniform(0, 3),
        'n_estimators': range(10, 75),  # nb de pas d'apprentissange pour chaque cas
    },
    cv=5, n_iter=100, n_jobs=multiprocessing.cpu_count()
)
search.fit(self._col_transformer.transform(train_df), train_labels)
regressor = XGBRegressor(verbose=0, objective='reg:squarederror', **search.best_params_)
regressor.fit(
    col_transformer.transform(train_df),
    train_labels
)
model = Pipeline(
    steps=[('preprocessor', col_transformer),
           ('regressor', regressor)]
)

update_registered_converter(
    XGBRegressor, 'XGBRegressor',
    calculate_linear_regressor_output_shapes,
    convert_xgboost
)
onnx = convert_sklearn(
    model,
    initial_types=_convert_dataframe_schema(self._for_eval_df)
)


def _column_tranformer_fitted_from_df(data: pd.DataFrame) -> ColumnTransformer:
    def transformer_for_column(column: pd.Series):
        if column.dtype in ['float64', 'float32']:
            return MinMaxScaler()
        if column.dtype in ['bool']:
            return 'passthrough'
        if column.dtype in ['O']:
            # TODO because of https://github.com/onnx/sklearn-onnx/issues/321
            return OrdinalEncoder()
        raise ValueError(f'Unexpected column dtype for {column.name}:{column.dtype}')

    return ColumnTransformer(
        [(col, transformer_for_column(data[col]), [col]) for col in data.columns],
        remainder='drop'
    ).fit(data)


def _convert_dataframe_schema(data: pd.DataFrame) -> List[Tuple[str, onnxtypes.DataType]]:
    def type_for_column(column: pd.Series):
        if column.dtype in ['float64', 'float32']:
            # onnx does not really support float64 (DoubleTensorType does not work with TreeEnsembleRegressor)
            return onnxtypes.FloatTensorType([None, 1])
        if column.dtype in ['bool']:
            return onnxtypes.BooleanTensorType([None, 1])
        if column.dtype in ['O']:
            return onnxtypes.StringTensorType([None, 1])
        raise ValueError(f'Unexpected column dtype for {column.name}:{column.dtype}')

    return [(col, type_for_column(data[col])) for col in data.columns]

```

**Comment by prabhat00155** [comment]
Sorry for the late reply, was busy with another work item. I seem to be getting a different error with your code. Anyways, we need to add support for boolean type(will add this work item). Do you get this error:https://github.com/onnx/sklearn-onnx/issues/399#issuecomment-583499082, with the code you pasted above?

**Comment by victornoel** [comment]
@prabhat00155 yes I do, I suppose we are limited by onnxruntime there?

**Comment by prabhat00155** [comment]
Are you running this on 'https://raw.githubusercontent.com/amueller/'
'scipy-2017-sklearn/091d371/notebooks/datasets/titanic3.csv' dataset as well?

**Comment by victornoel** [comment]
@prabhat00155 yes, you can also refer to https://gist.github.com/victornoel/c4da3089f6792ac1b6fdcdb583886f97: simply uncomment the line at the beginning to use the `female` boolean column instead of the `sex` one.

**Comment by prabhat00155** [comment]
Made some changes to your code(mapped bool to float):
```
import os
import warnings
from typing import List, Tuple

import onnxruntime as rt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from scipy.stats import randint as sp_randint, uniform as sp_uniform
from xgboost import XGBRegressor
from onnxmltools.convert.xgboost.operator_converters.XGBoost import convert_xgboost
import onnxmltools.convert.common.data_types as onnxtypes
from skl2onnx import update_registered_converter, convert_sklearn
from skl2onnx.common.shape_calculator import calculate_linear_regressor_output_shapes


warnings.simplefilter(action='ignore', category=FutureWarning)
os.environ["PYTHONWARNINGS"] = 'ignore'


def test():
    data = pd.read_csv(('https://raw.githubusercontent.com/amueller/'
                        'scipy-2017-sklearn/091d371/notebooks/datasets/titanic3.csv'))
    data['female'] = data['sex'] == 'female'
    #data.drop('sex', axis=1, inplace=True)
    #data = data[['age', 'fare', 'female', 'embarked', 'pclass', 'survived']]
    data = data[['age', 'fare', 'female', 'embarked', 'pclass', 'survived']]

    for col in data:
        dtype = data[col].dtype
        if dtype in ['float64', 'float32']:
            data[col].fillna(0., inplace=True)
        if dtype in ['int64']:
            data[col].fillna(0, inplace=True)
        elif dtype in ['O']:
            data[col].fillna('N/A', inplace=True)

    full_df = data.drop('survived', axis=1)
    full_labels = data['survived']

    train_df, test_df, train_labels, test_labels = train_test_split(
        full_df, full_labels, test_size=.2
    )

    col_transformer = _column_tranformer_fitted_from_df(full_df)

    search = RandomizedSearchCV(
        XGBRegressor(verbose=0, objective='reg:squarederror'),
        param_distributions={
            "colsample_bytree": sp_uniform(),
            "gamma": sp_uniform(.1, 1),
            'learning_rate': sp_uniform(.1, .6),
            'max_depth': sp_randint(10, 30),
            'min_child_weight': sp_uniform(0, 3),
            'n_estimators': range(10, 75),
        },
        cv=5, n_iter=10, n_jobs=-1
    )
    search.fit(col_transformer.transform(train_df), train_labels)
    regressor = XGBRegressor(verbose=0, objective='reg:squarederror', **search.best_params_)
    regressor.fit(
        col_transformer.transform(train_df),
        train_labels
    )
    model = Pipeline(
        steps=[('preprocessor', col_transformer),
               ('regressor', regressor)]
    )

    update_registered_converter(
        XGBRegressor, 'XGBRegressor',
        calculate_linear_regressor_output_shapes,
        convert_xgboost
    )
    onnx = convert_sklearn(
        model,
        initial_types=_convert_dataframe_schema(full_df)
    )

    session = rt.InferenceSession(onnx.SerializeToString())

    pred_skl = model.predict(test_df)
    pred_onx = _predict(session, test_df)

    diff = np.sort(np.abs(np.squeeze(pred_skl) - np.squeeze(pred_onx)))[-5:]
    print(diff)
    print('min(Y)-max(Y):', min(test_labels), max(test_labels))


def _column_tranformer_fitted_from_df(data: pd.DataFrame) -> ColumnTransformer:
    def transformer_for_column(column: pd.Series):
        if column.dtype in ['float64', 'float32', 'int64']:
            return MinMaxScaler()
        if column.dtype in ['bool']:
            return 'passthrough'
        if column.dtype in ['O']:
            return OneHotEncoder(drop='first')
        raise ValueError(f'Unexpected column dtype for {column.name}:{column.dtype}')

    return ColumnTransformer(
        [(col, transformer_for_column(data[col]), [col]) for col in data.columns],
        remainder='drop'
    ).fit(data)


def _convert_dataframe_schema(data: pd.DataFrame) -> List[Tuple[str, onnxtypes.DataType]]:
    def type_for_column(column: pd.Series):
        if column.dtype in ['float64', 'float32', 'bool']:
            # onnx does not really support float64 (DoubleTensorType does not work with TreeEnsembleRegressor)
            return onnxtypes.FloatTensorType([None, 1])
        if column.dtype in ['int64']:
            return onnxtypes.Int64TensorType([None, 1])
        #if column.dtype in ['bool']:
        #    return onnxtypes.BooleanTensorType([None, 1])
        if column.dtype in ['O']:
            return onnxtypes.StringTensorType([None, 1])
        raise ValueError(f'Unexpected column dtype for {column.name}:{column.dtype}')

    return [(col, type_for_column(data[col])) for col in data.columns]


def _predict(session: rt.InferenceSession, data: pd.DataFrame) -> pd.Series:
    def _correctly_typed_column(column: pd.Series) -> pd.Series:
        if column.dtype in ['float64', 'bool']:
            return column.astype(np.float32)
        return column

    def _correctly_shaped_values(values):
        return values.reshape((values.shape[0], 1))

    inputs = {
        c: _correctly_shaped_values(_correctly_typed_column(data[c]).values)
        for c in data.columns
    }

    return pd.Series(
        session.run(None, inputs)[0].reshape(-1),
        index=data.index
    )
```
If I call test() now, I get the following output:
[1.1920929e-07 1.1920929e-07 1.1920929e-07 1.1920929e-07 1.4901161e-07]
min(Y)-max(Y): 0 1

**Comment by victornoel** [comment]
@prabhat00155 yes, I already know that mapping the bool to float was a possibility.

I was wondering instead of I could be using boolean directly.

**Comment by prabhat00155** [comment]
Yeah, as I mentioned before, we need to add support for bool in the converters. I'll mark this issue as enhancement and evaluate the work that needs to be done to support bool. In the mean time, you may use the casting approach. Thanks!

**Comment by victornoel** [comment]
For the record, following the fix (#411), I tested again and there is now just one problem with concat:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/victor/test/test2.py", line 81, in test
    initial_types=_convert_dataframe_schema(full_df)
  File "/home/victor/.cache/pypoetry/virtualenvs/test-onnx-Gs-mCkZB-py3.7/src/skl2onnx/skl2onnx/convert.py", line 134, in convert_sklearn
    topology.compile()
  File "/home/victor/.cache/pypoetry/virtualenvs/test-onnx-Gs-mCkZB-py3.7/src/skl2onnx/skl2onnx/common/_topology.py", line 892, in compile
    self._infer_all_types()
  File "/home/victor/.cache/pypoetry/virtualenvs/test-onnx-Gs-mCkZB-py3.7/src/skl2onnx/skl2onnx/common/_topology.py", line 745, in _infer_all_types
    operator.infer_types()
  File "/home/victor/.cache/pypoetry/virtualenvs/test-onnx-Gs-mCkZB-py3.7/src/skl2onnx/skl2onnx/common/_topology.py", line 208, in infer_types
    shape_calc(self)
  File "/home/victor/.cache/pypoetry/virtualenvs/test-onnx-Gs-mCkZB-py3.7/src/skl2onnx/skl2onnx/shape_calculators/concat.py", line 43, in calculate_sklearn_concat
    inps, outs))
RuntimeError: Columns must have the same type. C++ backends do not support mixed types.
Inputs:
Variable(raw_name='variable', onnx_name='variable', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable1', type=FloatTensorType(shape=[None, 1]))
Variable(raw_name='female', onnx_name='female', type=BooleanTensorType(shape=[None, 1]))
Variable(raw_name='variable', onnx_name='variable2', type=FloatTensorType(shape=[None, 4]))
Variable(raw_name='variable', onnx_name='variable3', type=FloatTensorType(shape=[None, 1]))
Outputs:
Variable(raw_name='transformed_column', onnx_name='transformed_column', type=FloatTensorType(shape=[None, None]))
```

**Comment by xadupre** [comment]
See PR #445.

**Comment by victornoel** [comment]
@xadupre very nice, thx
