### ISSUE TITLE
AttributeError: 'numpy.uint8' object has no attribute 'encode'

### ISSUE THREAD

**Issue by sufiaji** [onnx/sklearn-onnx#476]
Hi Team,

I got such error when trying to convert ExtraTreesClassifier. This classifier was trained by another person in internet and I downloaded it as a pkl format, loaded using joblib. 
Please advise. Thank you.

![image](https://user-images.githubusercontent.com/7789546/83967196-8b87ca80-a8e9-11ea-9b42-2d4a83cda27d.png)

**Comment by xadupre** [comment]
Is it possible to get the full stack trace? I assume one part of the model is using uint8 but skl2onnx does not properly handle that case.

**Comment by sufiaji** [comment]
Hi,

Thanks for replying. Below is the complete error message thrown by Visual Studio Code. Please let me know if you need other information.

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS F:\Projects\libfaceid>  & 'C:\Python37\python.exe' 'c:\Users\Universe\.vscode\extensions\ms-python.python-2020.5.80290\pythonFiles\lib\python\debugpy\wheels\debugpy\launcher' '58148' '--' 'f:\Projects\libfaceid\sklearn2onnx.py'
C:\Python37\lib\site-packages\sklearn\base.py:189: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  def get_params(self, deep=True):
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Universe\.vscode\extensions\ms-python.python-2020.5.80290\pythonFiles\lib\python\debugpy\wheels\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Universe\.vscode\extensions\ms-python.python-2020.5.80290\pythonFiles\lib\python\debugpy\wheels\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Universe\.vscode\extensions\ms-python.python-2020.5.80290\pythonFiles\lib\python\debugpy\wheels\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "f:\Projects\libfaceid\sklearn2onnx.py", line 9, in <module>
    onx = convert_sklearn(clf_print, initial_types=[('x', FloatTensorType([None, 1536]))])
  File "C:\Python37\lib\site-packages\skl2onnx\convert.py", line 131, in convert_sklearn
    dtype=dtype)
  File "C:\Python37\lib\site-packages\skl2onnx\_parse.py", line 454, in parse_sklearn_model
    custom_parsers=custom_parsers)
  File "C:\Python37\lib\site-packages\skl2onnx\_parse.py", line 385, in parse_sklearn
    custom_parsers=custom_parsers)
  File "C:\Python37\lib\site-packages\skl2onnx\_parse.py", line 328, in _parse_sklearn_classifier
    classes = np.array([s.encode('utf-8') for s in classes])
  File "C:\Python37\lib\site-packages\skl2onnx\_parse.py", line 328, in <listcomp>
    classes = np.array([s.encode('utf-8') for s in classes])
AttributeError: 'numpy.uint8' object has no attribute 'encode'
PS F:\Projects\libfaceid>

**Comment by Rohan-Kumar** [comment]
Can we also have support for numpy bool?
Getting the following error:
AttributeError: 'numpy.bool_' object has no attribute 'encode'
