### ISSUE TITLE
Isssue in converting a tfidf-SVM pipeline

### ISSUE THREAD

**Issue by 123gkc** [onnx/sklearn-onnx#478]
Hello all -- Recently ran into onnx project in a conference. Trying to export some of my legacy systems to onnx so I can host them on model-server platforms directly.
 
I am trying to convert a sklearn pipeline that takes text as input and classifies it using tfidf feature extraction followed by SvmClassifier.
My code -> 
```
    print(X_train.shape)
    print(X_train.head())
    model_pipeline = Pipeline([
        ('vectorizer', TfidfVectorizer(stop_words=stopwords, lowercase=True, use_idf=True, ngram_range=(1,3), max_features=30000)),
        ('feature_selector', SelectKBest(chi2, k=1000)),
        ('classifier', SVC(class_weight='balanced', C=args.C, decision_function_shape='ovo', kernel='rbf', gamma='scale'))  
    ])
    
    model_pipeline.fit(X_train, y_train)
    initial_type = [('left_wing', StringTensorType([None, 1]))]
    onx = convert_sklearn(model_pipeline, "cv", initial_types=initial_type)
```

Stdout and stack trace -> 
```
(8320,)
0    in david i l c i a l one two zero seven at hot...
1    three payments i can make it three monthly pay...
2    if she's available at if he would like yeah ok...
3    be twenty eight dollars and fifty four cents t...
4    let me can i you on a brief hold really quick ...
Name: left_wing, dtype: object
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/skl2onnx/common/_container.py", line 380, in add_node
    node = make_node(op_type, inputs, outputs, name=name, **attrs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/skl2onnx/proto/onnx_helper_modified.py", line 58, in make_node
    for key, value in sorted(kwargs.items()))
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/skl2onnx/proto/onnx_helper_modified.py", line 58, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/skl2onnx/proto/onnx_helper_modified.py", line 173, in make_attribute
    [type(_) for _, __ in zip(value, range(0, 5))]))
ValueError: You passed in an iterable attribute but I cannot figure out its applicable type, key='coefficients', type=<class 'scipy.sparse.csr.csr_matrix'>, types=[<class 'scipy.sparse.csr.csr_matrix'>, <class 'scipy.sparse.csr.csr_matrix'>].

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "script.py", line 112, in <module>
    onx = convert_sklearn(model_pipeline, "cv", initial_types=initial_type)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/skl2onnx/convert.py", line 138, in convert_sklearn
    dtype=dtype, options=options)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/skl2onnx/common/_topology.py", line 977, in convert_topology
    conv(scope, operator, container)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/skl2onnx/operator_converters/support_vector_machines.py", line 95, in convert_sklearn_svm
    op_domain='ai.onnx.ml', **svm_attrs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/skl2onnx/common/_container.py", line 383, in add_node
    "".format(op_type, name)) from e
ValueError: Unable to create node 'SVMClassifier' with name='SVM'.
```

I am using skl2onnx==1.6.1 and sklearn==0.20.3

Any pointers/help will be greatly appreciated. Thanks!

**Comment by xadupre** [comment]
Is it possible to try with the version on master branch or the last released version on github (see release)?

**Comment by 123gkc** [comment]
Thanks for the quick response!

I just tried converting with skl2onnx==1.7.0 (the latest released version)
Facing same stack trace

**Comment by 123gkc** [comment]
Hi @xadupre -- Have you been able to replicate the issue?

**Comment by xadupre** [comment]
I was able to replicate. This important message is the following one:

```
ValueError: You passed in an iterable attribute but I cannot figure out its applicable type, key='coefficients', type=<class 'scipy.sparse.csr.csr_matrix'>, types=[<class 'scipy.sparse.csr.csr_matrix'>, <class 'scipy.sparse.csr.csr_matrix'>].
```

we assumed scikit-learn was using only dense coefficients in SVC. I'll if I can fix it.

**Comment by xadupre** [comment]
I fixed two bugs. The conversion should work. However, I found another bug in the runtime, onnxruntime does not seem to properly handle ngrams >= 2 with a stop word list.

**Comment by npapapietro** [comment]
Is there going to be any fix for this planned?
