### ISSUE TITLE
Error converting KNeighborsClassifier with numeric features

### ISSUE THREAD

**Issue by marinagre-px** [onnx/sklearn-onnx#482]
When converting KNN Classifier with numeric features, i.e.
```python
    numeric_features = ['path_len']
    numeric_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())])
```
AND

```python
 classifier = KNeighborsClassifier(n_neighbors=5, weights='distance')
```

the following error is thrown:
```
2020-06-09 14:12:16.709549 [E:onnxruntime:, sequential_executor.cc:281 Execute] Non-zero status code returned while running Scan node. Name:'Sc_Scan' Status Message: Subgraph must have the shape set for all outputs but next_out did not.
Traceback (most recent call last):
  File "/Users/marinagrechuhin/Development/Development-Tests/test_onnx/plot_complex_pipeline.py", line 349, in <module>
    pred_onx = sess.run(None, inputs)
  File "/Users/marinagrechuhin/Development/Development-Tests/test_onnx/venv/lib/python3.8/site-packages/onnxruntime/capi/session.py", line 111, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Scan node. Name:'Sc_Scan' Status Message: Subgraph must have the shape set for all outputs but next_out did not.
```
If using LinearRegression classifier, it works

**Comment by marinagre-px** [comment]
> That's a bug. In the mean time, can you try with the following option?
> 
> `convert_sklearn(..., options={KNeighborsClassifier: {'optim': 'cdist'}})`
> 
> It replaces the part which fails by an operator cdist (faster but this operator is the official onnx specification).

Thank you, this worked

**Comment by marinagre-px** [comment]
Also using version 1.7.0 without the options worked. 
Thanks
