### ISSUE TITLE
Must provide classlabels_strings or classlabels_int64s but not both.

### ISSUE THREAD

**Issue by janardangaikwad** [onnx/sklearn-onnx#607]
Trying to create an ONNX model for DecisionTreeClassifier for multi-output multi-lable classification. Conversion of the model to ONNX is successful, however, InferenceSession of model causing an error. Need help understanding the error and how to resolve it.

Source -

import sys
import pandas as pd
from onnxconverter_common import Int64TensorType
from skl2onnx import convert_sklearn
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
import onnxruntime as rt

def convert_dataframe_schema(xColumns):
    inputs = []
    for k in xColumns:
        t = Int64TensorType([None, 1])
        inputs.append((k, t))
    return inputs

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("arguments are not correct")
        sys.exit()

    path = sys.argv[1]
    alldata = pd.read_csv(path)
    alldata = alldata.astype('int64', copy=False) #convert to int64
    xColumns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10']
    yColumns = ['Y1', 'Y2','Y3', 'Y4', 'Y5', 'Y6']
    x = alldata.loc[:, xColumns]
    print(alldata)
    y = alldata.loc[:, yColumns]
    numeric_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())])
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', numeric_transformer, xColumns),
        ])
    inputs = convert_dataframe_schema(xColumns)
    y = alldata.loc[:, yColumns]
    model = Pipeline(steps=[('precprocessor', preprocessor), ('classifier', DecisionTreeClassifier())])
    model.fit(x, y)

    modeLName = 'DecisionTreeClassifier' + '.onnx'
    onx = convert_sklearn(model, initial_types=inputs, target_opset=12)
    with open(modeLName, "wb") as f:
        f.write(onx.SerializeToString())
    print("model generated - ", modeLName)
    sess = rt.InferenceSession(modeLName)

Error - 
2021-01-30 10:59:49.3834024 [W:onnxruntime:, graph.cc:84 onnxruntime::MergeShapeInfo] Error merging shape info for output. 'output_label' source:{,6} target:{}. Falling back to lenient merge.
2021-01-30 10:59:49.3930361 [E:onnxruntime:, inference_session.cc:1268 onnxruntime::InferenceSession::Initialize::<lambda_fa0ef5eee1ef668643e33f2e4e6892e1>::operator ()] Exception during initialization: C:\a\1\s\onnxruntime\core\provid
ers\cpu\ml\zipmap.cc:43 onnxruntime::ml::ZipMapOp::ZipMapOp classlabels_strings_.empty() ^ classlabels_int64s_.empty() was false. Must provide classlabels_strings or classlabels_int64s but not both.

Traceback (most recent call last):
  File "Tryouts\test.py", line 54, in <module>
    sess = rt.InferenceSession(modeLName)
  File "D:\Workdir\Syncplicity\MineProjects-V1\ModelView\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "D:\Workdir\Syncplicity\MineProjects-V1\ModelView\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 231, in _create_inference_session

**Comment by janardangaikwad** [comment]
By using options, removed the zip map from the model and it works perfectly.

Code - 
    options = {id(model.steps[-1][1]): {'zipmap': False}}
