### ISSUE TITLE
Converter fails if parenthesis in input name

### ISSUE THREAD

**Issue by dbanda** [onnx/sklearn-onnx#649]
The onnx converter creates an invalid model if there are parenthesis in the input name when passed as an initial type. The resulting onnx model is invalid and gives errors on inference .  It looks like onnx is replacing the parenthesis with underscores, is this expected behavior? 

```
# Train a model.
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y)
clr = RandomForestClassifier()
clr.fit(X_train, y_train)

# Convert into ONNX format
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType
initial_type = [('float(input)', FloatTensorType([None, 4]))]
onx = convert_sklearn(clr, initial_types=initial_type)
with open("rf_iris.onnx", "wb") as f:
    f.write(onx.SerializeToString())

# Compute the prediction with ONNX Runtime
import onnxruntime as rt
import numpy
sess = rt.InferenceSession("rf_iris.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
pred_onx = sess.run([label_name], {input_name: X_test.astype(numpy.float32)})[0]
```

Error:
```
Traceback (most recent call last):
  File "testskl.py", line 22, in <module>
    sess = rt.InferenceSession("rf_iris.onnx")
  File "/home/dbanda/miniconda3/envs/raven/lib/python3.6/site-packages/onnxruntime-1.7.0-py3.6-linux-x86_64.egg/onnxruntime/capi/onnxruntime_inference_collection.py", line 280, in __init__
    self._create_inference_session(providers, provider_options)
  File "/home/dbanda/miniconda3/envs/raven/lib/python3.6/site-packages/onnxruntime-1.7.0-py3.6-linux-x86_64.egg/onnxruntime/capi/onnxruntime_inference_collection.py", line 307, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from rf_iris.onnx failed:This is an invalid model. Node (TreeEnsembleClassifier) input arg (float_input_) does not have type information set by parent node.
```

Environment:
```
onnx==1.6.0
onnxconverter-common==1.8.1
onnxruntime==1.7.0
skl2onnx==1.8.0
```

**Comment by xadupre** [comment]
I may add an exception or a warning to tell the using not to use parenthesis in input names but I'd rather avoid automatically changing the name given by the user.
