### ISSUE TITLE
RuntimeError("Parameter 'min' must be a string or a float.") when converting AdaBoostClassifier

### ISSUE THREAD

**Issue by chernovars** [onnx/sklearn-onnx#663]
During conversion of an AdaBoostClassifier, the error was thrown:

Traceback (most recent call last):
  File "...\onnx_test.py", line 51, in <module>
    onnx(initial_type, e)
  File "...\onnx_test.py", line 25, in onnx
    onx = convert_sklearn(clr, initial_types=initial_type)
  File "C:\Users\Arseniy\AppData\Local\Programs\Python\Python39\lib\site-packages\skl2onnx\convert.py", line 160, in convert_sklearn
    onnx_model = convert_topology(topology, name, doc_string, target_opset,
  File "C:\Users\Arseniy\AppData\Local\Programs\Python\Python39\lib\site-packages\skl2onnx\common\_topology.py", line 1087, in convert_topology        
    conv(scope, operator, container)
  File "C:\Users\Arseniy\AppData\Local\Programs\Python\Python39\lib\site-packages\skl2onnx\common\_registration.py", line 29, in __call__
    return self._fct(*args)
  File "C:\Users\Arseniy\AppData\Local\Programs\Python\Python39\lib\site-packages\skl2onnx\operator_converters\ada_boost.py", line 299, in convert_sklearn_ada_boost_classifier
    cur_proba_name = _samme_r_proba(
  File "C:\Users\Arseniy\AppData\Local\Programs\Python\Python39\lib\site-packages\skl2onnx\operator_converters\ada_boost.py", line 82, in _samme_r_proba
    apply_clip(
  File "C:\Users\Arseniy\AppData\Local\Programs\Python\Python39\lib\site-packages\onnxconverter_common\onnx_ops.py", line 251, in apply_clip
    raise RuntimeError("Parameter 'min' must be a string or a float.")
RuntimeError: Parameter 'min' must be a string or a float.

So i tried to debug it, and 'min' in my case was of type np.float32 which is not in the list of allowed types: (np.ndarray, float, int)

I changed the library-code so that allowed types are  (np.ndarray, float, int, np.float32) and the error was gone. The conversion finished successfully then, and prediction worked without errors. Did not check if it predicted something meaningful though.

Have a nice day!

**Comment by xadupre** [comment]
Fixes by #682.
