### ISSUE TITLE
Cannot Chain OnnxOpeartor with OnnxSubOpearator

### ISSUE THREAD

**Issue by busFred** [onnx/sklearn-onnx#675]
In the [tutorial](http://onnx.ai/sklearn-onnx/auto_tutorial/plot_kcustom_converter_wrapper.html), an OnnxSubOperator is followed by OnnxIdentity (subclass of OnnxOperator).
```
def decorrelate_transformer_converter(scope, operator, container):
    op = operator.raw_operator
    opv = container.target_opset
    out = operator.outputs

    # We retrieve the unique input.
    X = operator.inputs[0]

    # We tell in ONNX language how to compute the unique output.
    # op_version=opv tells which opset is requested
    subop = OnnxSubOperator(op.pca_, X, op_version=opv)
    Y = OnnxIdentity(subop, op_version=opv, output_names=out[:1])
    Y.add_to(scope, container)
```
However, the other way around -- an instance of OnnxOperator followed by an OnnxSubOperator -- causes an error. Both OnnxNormalizer and OnnxIdentity are instances of OnnxOperator.
```
def decorrelate_transformer_converter(scope, operator, container):
    op = operator.raw_operator
    opv = container.target_opset
    out = operator.outputs

    # We retrieve the unique input.
    X = operator.inputs[0]

    # We tell in ONNX language how to compute the unique output.
    # op_version=opv tells which opset is requested
    X = OnnxNormalizer(X, norm="L2", op_version=opv)
    subop = OnnxSubOperator(op.pca_, X, op_version=opv)
    Y = OnnxIdentity(subop, op_version=opv, output_names=out[:1])
    Y.add_to(scope, container)
```
Causes the following error.
```
Traceback (most recent call last):
  File "/home/fred/Documents/research/sklearn_plugins/test/converter_wrapper.py", line 191, in <module>
    onx = to_onnx(dec, X.astype(numpy.float32))
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx/convert.py", line 210, in to_onnx
    return convert_sklearn(model, initial_types=initial_types,
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx/convert.py", line 160, in convert_sklearn
    onnx_model = convert_topology(topology, name, doc_string, target_opset,
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx/common/_topology.py", line 1064, in convert_topology
    for operator in topology.topological_operator_iterator():
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx/common/_topology.py", line 623, in topological_operator_iterator
    if (all(variable.is_fed for variable in operator.inputs)
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx/common/_topology.py", line 623, in <genexpr>
    if (all(variable.is_fed for variable in operator.inputs)
AttributeError: 'OnnxNormalizer' object has no attribute 'is_fed'
```
It seems the `inputs` argument of OnnxSubOperator only accepts `skl2onnx.common._topology.Variable` type. But I couldn't get OnnxNormalizer to generate a valid output that is of `Variable` type.

If I try to access OnnxNormalizer.outputs, I get: `RuntimeError: Method add_to was not called.`
After I call `OnnxNormalizer.add_to(scope, container)` and then access `OnnxNormalizer.outputs`, the `OnnxNormalizer.outputs` is a List[str], which causes 'str' object has no attribute 'is_fed'
```
def decorrelate_transformer_converter(scope, operator, container):
    op = operator.raw_operator
    opv = container.target_opset
    out = operator.outputs

    # We retrieve the unique input.
    X = operator.inputs[0]

    # We tell in ONNX language how to compute the unique output.
    # op_version=opv tells which opset is requested
    X = OnnxNormalizer(X, norm="L2", op_version=opv)
    X.add_to(scope,container)
    subop = OnnxSubOperator(op.pca_, X.outputs[0], op_version=opv)
    Y = OnnxIdentity(subop, op_version=opv, output_names=out[:1])
    Y.add_to(scope, container)
```
```
Traceback (most recent call last):
  File "/home/fred/Documents/research/sklearn_plugins/test/converter_wrapper.py", line 192, in <module>
    onx = to_onnx(dec, X.astype(numpy.float32))
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx/convert.py", line 210, in to_onnx
    return convert_sklearn(model, initial_types=initial_types,
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx/convert.py", line 160, in convert_sklearn
    onnx_model = convert_topology(topology, name, doc_string, target_opset,
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx/common/_topology.py", line 1064, in convert_topology
    for operator in topology.topological_operator_iterator():
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx/common/_topology.py", line 623, in topological_operator_iterator
    if (all(variable.is_fed for variable in operator.inputs)
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx/common/_topology.py", line 623, in <genexpr>
    if (all(variable.is_fed for variable in operator.inputs)
AttributeError: 'str' object has no attribute 'is_fed'
```

**Comment by xadupre** [comment]
There were two classes OnnxSubEstimator and OnnxSubOperator in the previous release. I deprecated OnnxSubOperator in the latest release 1.9.0 (https://github.com/onnx/sklearn-onnx/releases), OnnxIdentity is no longer needed (see PR #676).

**Comment by busFred** [comment]
With OnnxSubEstimator, I have resolved the problem.
