### ISSUE TITLE
Version 1.9 apply_normalizer does not support double

### ISSUE THREAD

**Issue by busFred** [onnx/sklearn-onnx#678]
In my converter function, I have the following.
```
def spherical_kmeans_converter(scope: Scope, operator: Operator,
                               container: ModelComponentContainer):
    """The ONNX converter for sklearn_plugins.cluster.SphericalKMeans.

    Original SphericalKMeans Implementation:
    ```
    # preprocess input
    if skm.normalize:
        X = normalize(X, norm="l2", axis=1, copy=skm.copy)
    # each features in the dataset has zero mean and unit variance; dataset level
    if skm.standarize:
        X = skm.__std_scalar_.transform(X, copy=copy)
    # PCA whiten
    X = skm.__pca_.transform(X)
    # calculate projection
    proj: np.ndarray = np.matmul(X, centroids)
    # calculate lables
    labels: np.ndarray = np.argmax(S_proj, axis=1)
    ```

    Args:
        scope (Scope): [description]
        operator (Operator): [description]
        container (ModelComponentContainer): [description]
    """
    skm: SphericalKMeans = operator.raw_operator
    op_version: Union[int, None] = container.target_opset
    op_outputs: List[Variable] = operator.outputs
    # retreive input
    input: Variable = operator.inputs[0]
    np_dtype = guess_numpy_type(input.type)
    # normalize input
    normalize_op: Union[OnnxOperator, Variable] = input
    if skm.normalize == True:
        normalize_op = OnnxSubEstimator(Normalizer(norm="l2"),
                                        normalize_op,
                                        op_versionrow_norms=op_version)
        # normalize_op = OnnxNormalizer(input, norm="L2", op_version=op_version)
    # standardize input
    std_scalar_op: Union[OnnxOperator, Variable] = normalize_op
    if skm.standardize == True:
        std_scalar_op = OnnxSubEstimator(skm.std_scalar_,
                                         normalize_op,
                                         op_versionrow_norms=op_version)
    # pca whitening
    pca_op: OnnxOperator = OnnxSubEstimator(skm.pca_,
                                            std_scalar_op,
                                            op_version=op_version)
    # calculate projection
    proj_op: OnnxOperator = OnnxMatMul(pca_op,
                                       skm.centroids_.astype(np_dtype),
                                       op_version=op_version,
                                       output_names=[op_outputs[1]])
    proj_op.add_to(scope=scope, container=container)
    labels_op: OnnxOperator = OnnxArgMax(proj_op,
                                         op_version=op_version,
                                         output_names=[op_outputs[0]])
    labels_op.add_to(scope=scope, container=container)
```
When I try to convert the model with the following:
```
onx: ModelProto
try:
    onx = to_onnx(skm, X.astype(np.float64))
except Exception as e:
    traceback.print_exception(type(e), e, e.__traceback__)
```
I get the following exception:
```
Traceback (most recent call last):
  File "/home/fred/Documents/research/sklearn_plugins/test/sklearn_plugins/cluster/test_spherical_kmeans_export.py", line 64, in <module>
    onx = to_onnx(skm, X.astype(np.float64))
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx-1.9.0-py3.8.egg/skl2onnx/convert.py", line 207, in to_onnx
    return convert_sklearn(model, initial_types=initial_types,
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx-1.9.0-py3.8.egg/skl2onnx/convert.py", line 157, in convert_sklearn
    onnx_model = convert_topology(topology, name, doc_string, target_opset,
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx-1.9.0-py3.8.egg/skl2onnx/common/_topology.py", line 1180, in convert_topology
    conv(scope, operator, container)
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx-1.9.0-py3.8.egg/skl2onnx/common/_registration.py", line 26, in __call__
    return self._fct(*args)
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx-1.9.0-py3.8.egg/skl2onnx/operator_converters/normaliser.py", line 27, in convert_sklearn_normalizer
    apply_normalizer(
  File "/home/fred/anaconda3/envs/sklearn_plugins/lib/python3.8/site-packages/skl2onnx-1.9.0-py3.8.egg/skl2onnx/common/_apply_operation.py", line 44, in apply_normalizer
    raise NotImplementedError(
NotImplementedError: Normalization not implemented for norm 'L2'.
```
I dive into _apply_operation.py, I found out that for L2 normalization is indeed unimplemented for double type:
```
def apply_normalizer(scope, inputs, outputs, container,
                     norm, use_float):
    """
    Adds operator Normalizer if *use_float* is true,
    otherwise, uses *ReduceSum* + *Div*. *Normalizer*
    always produces float according to ONNX speciciations.
    """
    input = inputs[0] if isinstance(inputs, list) else inputs
    output = outputs[0] if isinstance(outputs, list) else outputs

    if use_float:
        container.add_node(
            'Normalizer', input, output,
            op_domain='ai.onnx.ml', norm=norm,
            name=scope.get_unique_operator_name('Normalizer'))
    else:
        # Normalizer only produces floats.
        if norm == 'L1':
            norm = scope.get_unique_variable_name('norm')

            if container.target_opset < 13:
                container.add_node(
                    'ReduceSum', input, norm, axes=[1], keepdims=1,
                    name=scope.get_unique_operator_name('NormalizerNorm'))
            else:
                axis_name = scope.get_unique_variable_name('axis')
                container.add_initializer(
                    axis_name, onnx_proto.TensorProto.INT64, [1], [1])
                container.add_node(
                    'ReduceSum', [input, axis_name], norm, keepdims=1,
                    name=scope.get_unique_operator_name('ReduceSum'))
            apply_div(  # noqa
                scope, [input, norm], output, container,
                operator_name=scope.get_unique_operator_name(
                    'NormalizerNorm'))
        else:
            raise NotImplementedError(
                "Normalization not implemented for norm %r." % norm)
```
The same file exist in version 1.8.1, but the content of the file is empty.

**Comment by xadupre** [comment]
Closing the issue as the PR was merged.
