### ISSUE TITLE
Converter for pyod.models.iforest.IForest

### ISSUE THREAD

**Issue by hanzigs** [onnx/sklearn-onnx#685]
Is it possible to get converter for pyod anomaly detection models? 
https://pyod.readthedocs.io/en/latest/_modules/pyod/models/iforest.html

pyod Iforest is a Wrapper of scikit-learn Isolation Forest with more functionalities.

```
Traceback (most recent call last):

  File "<ipython-input-91-f753e8bf7b2f>", line 1, in <module>
    IFOnnx_model = convert_sklearn(model1, initial_types=initial_type)

  File "C:\Users\pl\Anaconda3\lib\site-packages\onnxmltools\convert\main.py", line 66, in convert_sklearn
    custom_conversion_functions, custom_shape_calculators)

  File "C:\Users\pl\Anaconda3\lib\site-packages\skl2onnx\convert.py", line 150, in convert_sklearn
    topology.compile()

  File "C:\Users\pl\Anaconda3\lib\site-packages\skl2onnx\common\_topology.py", line 903, in compile
    self._infer_all_types()

  File "C:\Users\pl\Anaconda3\lib\site-packages\skl2onnx\common\_topology.py", line 756, in _infer_all_types
    operator.infer_types()

  File "C:\Users\pl\Anaconda3\lib\site-packages\skl2onnx\common\_topology.py", line 215, in infer_types
    type(self.raw_operator)))

MissingShapeCalculator: Unable to find a shape calculator for type '<class 'pyod.models.iforest.IForest'>'.
It usually means the pipeline being converted contains a
transformer or a predictor with no corresponding converter
implemented in sklearn-onnx. If the converted is implemented
in another library, you need to register
the converted so that it can be used by sklearn-onnx (function
update_registered_converter). If the model is not yet covered
by sklearn-onnx, you may raise an issue to
https://github.com/onnx/sklearn-onnx/issues
to get the converter implemented or even contribute to the
project. If the model is a custom model, a new converter must
be implemented. Examples can be found in the gallery.
```
sample code for IForest
```
import pandas as pd
from pyod.models.iforest import IForest
from sklearn.preprocessing import MinMaxScaler

data1 = {'First':  [500,500,400,100,200,300,100],
         'Second': ['a','b','a','b','a','b','c'],
         }
df1 = pd.DataFrame(data1,columns=['First','Second'])
dumdf1 = pd.get_dummies(df1) 
scaler = MinMaxScaler()
scaler.partial_fit(dumdf1)
sc_data = scaler.transform(dumdf1)
model1 = IForest(n_estimators=10,
               bootstrap=True,
               behaviour='new',
               contamination=0.1,
               random_state=np.random.RandomState(42),
               verbose=1,
               n_jobs=-1).fit(sc_data)
feature_names2 = dumdf1.columns

from onnxmltools.convert.common.data_types import FloatTensorType
from onnxmltools import convert_sklearn

initial_type = [('float_input', FloatTensorType([None, len(feature_names2)]))]
IFOnnx_model = convert_sklearn(model1, initial_types=initial_type)
```

Thanks in advance

**Comment by xadupre** [comment]
There are many extensions to scikit-learn and sklearn-onnx cannot support all of them. You may follow the tutorial to implement a new converter [Implement a new converter](http://onnx.ai/sklearn-onnx/auto_tutorial/plot_icustom_converter.html). I could also add an example to the documentation to show how to do it. What do you prefer?

**Comment by hanzigs** [comment]
Thanks for the reply, Could you please add an example.

**Comment by hanzigs** [comment]
I just tried the converter, i'm getting below error
```
from skl2onnx.common.data_types import guess_numpy_type
Traceback (most recent call last):

  File "<ipython-input-14-4340147dd8f7>", line 1, in <module>
    from skl2onnx.common.data_types import guess_numpy_type

ImportError: cannot import name 'guess_numpy_type' from 'skl2onnx.common.data_types' (C:\Users\pl\Anaconda3\lib\site-packages\skl2onnx\common\data_types.py)
```
pip install skl2onnx getting 1.7.0, pypi has got 1.9.0

**Comment by hanzigs** [comment]
Installed from Source and got the 1.9.0, above not there any more, Thanks

**Comment by hanzigs** [comment]
'IForest' object doesn't have 'coef_', it has only decision_scores_, may I know how to proceed in shape_calculator
or
I will wait for your example
Thanks

**Comment by hanzigs** [comment]
I tried the following by using decision_scores_ in place of coef_ and op.decision_scores_.mean() in place of op.mean_
```
def pyod_models_iforest_IForest_shape_calculator(operator):
    op = operator.raw_operator
    input_type = operator.inputs[0].type.__class__
    input_dim = operator.inputs[0].type.shape[0]
    ds = op.decision_scores_.reshape(1,-1)
    output_type = input_type([input_dim, ds.shape[1]]) 
    operator.outputs[0].type = output_type
  
def pyod_models_iforest_IForest_converter(scope, operator, container):
    op = operator.raw_operator
    opv = container.target_opset
    out = operator.outputs

    # We retrieve the unique input.
    X = operator.inputs[0]

    # In most case, computation happen in floats.
    # But it might be with double. ONNX is very strict
    # about types, every constant should have the same
    # type as the input.
    dtype = guess_numpy_type(X.type)

    # We tell in ONNX language how to compute the unique output.
    # op_version=opv tells which opset is requested
    Y = OnnxMatMul(
        OnnxSub(X, op.decision_scores_.mean().reshape(1,-1).astype(dtype), op_version=opv),
        op.decision_scores_.astype(dtype),
        op_version=opv, output_names=out[:1])
    Y.add_to(scope, container)
  
update_registered_converter(
    IForest, "pyodIForest",
    pyod_models_iforest_IForest_shape_calculator,
    pyod_models_iforest_IForest_converter)

try:
    to_onnx(if_model, data.astype(np.float32))
except Exception as e:
    print(e)
    
onx = to_onnx(if_model, data.astype(np.float32))

sess = InferenceSession(onx.SerializeToString())
```
When creating InferenceSession end up in following error
```
    sess = InferenceSession(onx.SerializeToString())

  File "C:\Users\pl\Anaconda3\lib\site-packages\onnxruntime\capi\session.py", line 158, in __init__
    self._load_model(providers)

  File "C:\Users\pl\Anaconda3\lib\site-packages\onnxruntime\capi\session.py", line 177, in _load_model
    self._sess.load_model(providers)

Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Ma_MatMul) Op (MatMul) [ShapeInferenceError] Incompatible dimensions for matrix multiplication
```

**Comment by hanzigs** [comment]
Thank you very much for the prompt action for the request, much appreciated

**Comment by hanzigs** [comment]
I tried the converter from https://github.com/onnx/sklearn-onnx/pull/690/commits/d26e5db9df7ef1d51b618e1c24fb2c301ba1a46d

For the same example data
getting an runtimeerror
```
RuntimeError                              Traceback (most recent call last)
c:\ad\ad.py in 
----> 575 onx = to_onnx(model1, initial_types=initial_type)

~\Anaconda3\lib\site-packages\skl2onnx\convert.py in to_onnx(model, X, name, initial_types, target_opset, options, white_op, black_op, final_types, dtype)
    209                            name=name, options=options,
    210                            white_op=white_op, black_op=black_op,
--> 211                            final_types=final_types, dtype=dtype)
    212 
    213 

~\Anaconda3\lib\site-packages\skl2onnx\convert.py in convert_sklearn(model, name, initial_types, doc_string, target_opset, custom_conversion_functions, custom_shape_calculators, custom_parsers, options, intermediate, white_op, black_op, final_types, dtype)
    157     onnx_model = convert_topology(topology, name, doc_string, target_opset,
    158                                   options=options,
--> 159                                   remove_identity=not intermediate)
    160 
    161     return (onnx_model, topology) if intermediate else onnx_model

~\Anaconda3\lib\site-packages\skl2onnx\common\_topology.py in convert_topology(topology, model_name, doc_string, target_opset, channel_first_inputs, options, remove_identity)
   1178                               type(getattr(operator, 'raw_model', None))))
   1179         container.validate_options(operator)
-> 1180         conv(scope, operator, container)
   1181 
   1182     container.ensure_topological_order()

~\Anaconda3\lib\site-packages\skl2onnx\common\_registration.py in __call__(self, *args)
     24             if args[1].raw_operator is not None:
     25                 args[2]._get_allowed_options(args[1].raw_operator)
---> 26         return self._fct(*args)
     27 
     28     def get_allowed_options(self):

c:\ad\ad.py in pyod_iforest_converter(scope, operator, container)
     529     clipped = OnnxClip(scaled_centered, np.array([0], dtype=dtype),
     530                        np.array([1], dtype=dtype),
---> 531                        op_version=opv)
     532     clipped_ = OnnxAdd(
     533         OnnxMul(clipped, np.array([-1], dtype=dtype),

~\Anaconda3\lib\site-packages\skl2onnx\algebra\onnx_ops.py in __init__(self, *args, **kwargs)
    105                     "coo_matrix)." % (
    106                         type(a), i, class_name))
--> 107         OnnxOperator.__init__(self, *args, **kwargs)
    108 
    109     newclass = type(class_name, (OnnxOperator,),

~\Anaconda3\lib\site-packages\skl2onnx\algebra\onnx_operator.py in __init__(self, op_version, output_names, domain, *inputs, **kwargs)
    323                     "class opset={})".format(
    324                         self.operator_name, *self.input_range,
--> 325                         len(self.inputs), op_version, self.op_version))
    326 
    327         # check output

RuntimeError: Operator 'Clip' expects a number of inputs in [1, 1] not 3 (expected opset=10, class opset=6)
```

May i have some help on this please, Thanks in Advance

**Comment by xadupre** [comment]
Thanks for letting me know. I'll close the issue. Feel free to reopen it if something fails again.

**Comment by JUJI0709** [comment]
Hi, is there similar method can convert unsupervised algorithm situation in isolation forest?
