### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException

### ISSUE THREAD

**Issue by guici123** [onnx/sklearn-onnx#764]
Traceback (most recent call last):
  File "D:/pycharmprojects/resume_determine/methods/LR/LR_onnx.py", line 198, in <module>
    sess = rt.InferenceSession("pipeline_lr_char_100.onnx")
  File "E:\Python37\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "E:\Python37\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 321, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)

onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cpu\nn\string_normalizer.cc:289 onnxruntime::StringNormalizer::StringNormalizer p.second was false. Duplicate stopwords not allowed

**Comment by xadupre** [comment]
Closing the issue. Feel free to reopen.
