### ISSUE TITLE
MissingShapeCalculator for `skl2onnx.sklapi.woe_transformer.WOETransformer`

### ISSUE THREAD

**Issue by supercharleszhu** [onnx/sklearn-onnx#768]
Hi team, I am trying to build an onnx graph manually using helper function, however we are meeting the following issue when n trying to build the graph
```
Traceback (most recent call last):
  File "/Users/chzhu/PycharmProjects/pythonProject/ads_full_model_for_triton_v7.py", line 2286, in <module>
    build_model('ads_full_model_for_triton_v7.onnx')
  File "/Users/chzhu/PycharmProjects/pythonProject/ads_full_model_for_triton_v7.py", line 398, in build_model
    page_view_bucketize_subgraph = to_onnx(page_view_woe, bucketize_input_template)
  File "/usr/local/lib/python3.9/site-packages/skl2onnx/convert.py", line 251, in to_onnx
    return convert_sklearn(model, initial_types=initial_types,
  File "/usr/local/lib/python3.9/site-packages/skl2onnx/convert.py", line 182, in convert_sklearn
    onnx_model = convert_topology(
  File "/usr/local/lib/python3.9/site-packages/skl2onnx/common/_topology.py", line 1333, in convert_topology
    topology.convert_operators(container=container, verbose=verbose)
  File "/usr/local/lib/python3.9/site-packages/skl2onnx/common/_topology.py", line 1169, in convert_operators
    self.call_shape_calculator(operator)
  File "/usr/local/lib/python3.9/site-packages/skl2onnx/common/_topology.py", line 1014, in call_shape_calculator
    operator.infer_types()
  File "/usr/local/lib/python3.9/site-packages/skl2onnx/common/_topology.py", line 567, in infer_types
    raise MissingShapeCalculator(
skl2onnx.common.exceptions.MissingShapeCalculator: Unable to find a shape calculator for type '<class 'skl2onnx.sklapi.woe_transformer.WOETransformer'>'.
It usually means the pipeline being converted contains a
transformer or a predictor with no corresponding converter
implemented in sklearn-onnx. If the converted is implemented
in another library, you need to register
the converted so that it can be used by sklearn-onnx (function
update_registered_converter). If the model is not yet covered
by sklearn-onnx, you may raise an issue to
https://github.com/onnx/sklearn-onnx/issues
to get the converter implemented or even contribute to the
project. If the model is a custom model, a new converter must
be implemented. Examples can be found in the gallery.

```
However I can see the WOETransformer in the site packages in skl2onnx 1.9.3 version. Do you have any insights on that?

**Comment by xadupre** [comment]
WOETransformer was added as an example in the documentation. The converter is implemented in this example [Converter for WOEEncoder from categorical_encoder](http://onnx.ai/sklearn-onnx/auto_tutorial/plot_catwoe_transformer.html). It was added in the default list of converters. It is something you would like to see?

**Comment by xadupre** [comment]
The specific line to ad is the following one: `import skl2onnx.sklapi.register`.

May I close the issue?

**Comment by xadupre** [comment]
I'll close the issue feel free to reopen it.
