### ISSUE TITLE
Pyinstaller compatibility

### ISSUE THREAD

**Issue by skornel02** [onnx/sklearn-onnx#922]
Hi,
I am currently trying to compile the following simple python script to an executable with PyInstaller:

```python
import skl2onnx
print("hello world!")
```

I am not very familiar with the ecosystem so I'm interested if this is something that may or may not even work or has anyone managed to make this work.

<details> 
  <summary>Output of the executable (on Windows w/ Python 3.7.1)</summary>
  <pre>
Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "skl2onnx\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "skl2onnx\convert.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "skl2onnx\common\_topology.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "skl2onnx\common\_container.py", line 89, in <module>
  File "skl2onnx\common\_container.py", line 49, in _get_operation_list
  File "inspect.py", line 973, in getsource
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code
[1788] Failed to execute script 'test' due to unhandled exception!
   </pre>
</details>

Thank you for your help in advance!

**Comment by xadupre** [comment]
I guess inpsect expects to see physical files but pyinstaller removes the physical file. It could happen with other modules. The code using inpsect is just doing validation and could be disabled.
