### ISSUE TITLE
VotingClassifier to onnx does not support xgb and lgb as base estimators

### ISSUE THREAD

**Issue by singaln** [onnx/sklearn-onnx#936]
Code:
```python
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier, RandomForestClassifier
from sklearn.datasets import load_breast_cancer
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from skl2onnx import convert_sklearn, update_registered_converter
from skl2onnx.common.data_types import FloatTensorType, Int64TensorType, StringTensorType
from sklearn.compose import ColumnTransformer

param_dict = {}


def convert_dataframe_schema(train_data, drop=None):
    inputs = []
    for k, v in zip(train_data.columns, train_data.dtypes):
        if drop is not None and k in drop:
            continue
        if v == 'int64':
            t = Int64TensorType([None, 1])
        elif v == "float32":
            t = FloatTensorType([None, 1])
        elif v == "float64":
            t = FloatTensorType([None, 1])
        else:
            t = StringTensorType([None, 1])
        inputs.append((k, t))
    return inputs


lgb_model = LGBMClassifier().set_params(**param_dict.get('lightgbm', {}))
xgb_model = XGBClassifier().set_params(**param_dict.get('xgboost', {}))
# rf_model = RandomForestClassifier().set_params(**param_dict.get("rf", {}))
lr_model = LogisticRegression().set_params(**param_dict.get('lr', {}))
model_classifier = VotingClassifier(estimators=[('lightgbm', lgb_model), ('xgboost', xgb_model), ('lr', lr_model)],
                                    voting='soft', weights=np.ones(3), n_jobs=3, flatten_transform=False)
# model_classifier = VotingClassifier(estimators=[('rf', rf_model),("lr", lr_model)], voting="soft", weights=np.ones(2), flatten_transform=False)
data = load_breast_cancer()
data_columns = [col.replace(" ", "_") for col in data["feature_names"]]
data_df = pd.DataFrame(data=data.data, columns=data_columns)
data_df['target'] = pd.Series(data.target)
X_data, X_test = train_test_split(data_df)
data_X, data_y = X_data.iloc[:, :-1], X_data.iloc[:, -1]
test_X, test_y = X_test.iloc[:, :-1], X_test.iloc[:, -1]

numeric_transformer = Pipeline(steps=[('scaler', StandardScaler())])
preprocessor = ColumnTransformer(transformers=[('num', numeric_transformer, data_columns)])
model = Pipeline([("mapper", preprocessor), ("classifier", model_classifier)])
model.fit(data_X, data_y)
initial_inputs = convert_dataframe_schema(train_data=data_X)

model_onnx = convert_sklearn(model=model, name="voting", initial_types=initial_inputs,
                             target_opset={'': 12, 'ai.onnx.ml': 2}, verbose=True)
with open("./output", "wb") as f:
    f.write(model_onnx.SerializeToString())
```
Error:
```
[convert_sklearn] parse_sklearn_model
[convert_sklearn] convert_topology
[convert_operators] begin
[convert_operators] iteration 1 - n_vars=0 n_ops=4
[call_converter] call converter for 'SklearnConcat'.
[call_converter] call converter for 'SklearnScaler'.
Traceback (most recent call last):
  File "D:\bm_v3\business_modeling\src\bm\model\test.py", line 61, in <module>
    model_onnx = convert_sklearn(model=model, name="voting", initial_types=initial_inputs,
  File "D:\ProgramData\Anaconda3\envs\ml\lib\site-packages\skl2onnx\convert.py", line 184, in convert_sklearn
    onnx_model = convert_topology(
  File "D:\ProgramData\Anaconda3\envs\ml\lib\site-packages\skl2onnx\common\_topology.py", line 1421, in convert_topology
    topology.convert_operators(container=container, verbose=verbose)
  File "D:\ProgramData\Anaconda3\envs\ml\lib\site-packages\skl2onnx\common\_topology.py", line 1256, in convert_operators
[call_converter] call converter for 'SklearnVotingClassifier'.
    self.call_converter(operator, container, verbose=verbose)
  File "D:\ProgramData\Anaconda3\envs\ml\lib\site-packages\skl2onnx\common\_topology.py", line 1062, in call_converter
    conv(self.scopes[0], operator, container)
  File "D:\ProgramData\Anaconda3\envs\ml\lib\site-packages\skl2onnx\common\_registration.py", line 26, in __call__
    return self._fct(*args)
  File "D:\ProgramData\Anaconda3\envs\ml\lib\site-packages\skl2onnx\operator_converters\voting_classifier.py", line 49, in convert_voting_classifier
    op_type = sklearn_operator_name_map[type(estimator)]
KeyError: <class 'lightgbm.sklearn.LGBMClassifier'>
```

**Comment by xadupre** [comment]
The error message is not helpful but it comes from the fact skl2onnx does not have any converter for lightgbm unless one is registerd. The tutorial explains how to do it: https://onnx.ai/sklearn-onnx/auto_tutorial/plot_gexternal_lightgbm.html, https://onnx.ai/sklearn-onnx/auto_tutorial/plot_gexternal_xgboost.html.

**Comment by xadupre** [comment]
Closing the issue, feel free to reopen it.
